### ISSUE TITLE
sample to use it

### ISSUE THREAD

**Issue by nprasaanth07** [camilin87/debug-ef-core#1]
Hi , thanks for creating the package . But I still cannot figure out how to use it . I have set the EnableLogging method in my context class as you mentioned . But in my client when I try to log the SQL , I neither get to see context.Database.Log ... not am I able to do IQueryable.ToString to get the SQL like EF6 .

Could you provide some samples on the client please ? As to how exactly to get the SQL from IQueryable .

**Comment by cshtdd** [comment]
The SQL would be in your Log4Net logs.
You don't have to write any additional code to see the SQL. Run the application as you'd normally do and then look at your log4net logs.

**Comment by cshtdd** [comment]
Here's a sample project https://github.com/camilin87/debug-ef-core-sample
